# Generated by Django 3.0.6 on 2020-10-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200722_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='open_to_work',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
