# Generated by Django 3.0.6 on 2020-10-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_auto_20200829_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='joblist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='jobcat', to='job.Job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.Job'),
        ),
    ]
