# Generated by Django 3.0.6 on 2020-10-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_auto_20201008_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='joblist',
        ),
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.Job'),
        ),
    ]
